use super::*;
use pretty_assertions::assert_eq;
use serde_json::json;

// Generated by existing Python event_for; independently rechecked by verify_goldens.py.
const ASCII: &str = r#"{"content": "PF-80-S01: worker reports working. Recovery test passed; human acceptance still pending.\nProgress observation only; no acceptance or task-completion claim.", "coverage": "manager_observed_worker_report_not_independent_acceptance", "goal": {"active": true, "id": "PF-80-S01", "status": "reported_working"}, "id": "cc-cf3440216007cdf72d47f5467dbdc482d916b96d76635bc3537a222b83d67373", "instanceId": "corbanu-control", "kind": "goal", "occurredAt": "2026-09-11T12:00:00.000Z", "repository": {"branch": "test/fixture", "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "label": "Corbanu Terminal"}, "sequence": 0, "sessionId": "run-1", "taskIds": ["task-a", "task-b"], "turnId": "PF-80-S01", "workspaceId": "synthetic-workspace"}"#;
const UNICODE: &str = r#"{"content": "PF-80-S01: worker reports working. \u732b \ud83d\ude00 caf\u00e9 \"quote\" \\ path\n\tDEL\u007f\nProgress observation only; no acceptance or task-completion claim.", "coverage": "manager_observed_worker_report_not_independent_acceptance", "goal": {"active": true, "id": "PF-80-S01", "status": "reported_working"}, "id": "cc-28c67ff9cce626839667b732480de28d352391b0846abcbab2e8638c58eaccc4", "instanceId": "corbanu-control", "kind": "goal", "occurredAt": "2026-09-11T12:00:00.000Z", "repository": {"branch": "test/\u732b\ud83d\ude00", "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "label": "Corbanu Terminal"}, "sequence": 0, "sessionId": "run-1", "taskIds": ["task-a", "task-b"], "turnId": "PF-80-S01", "workspaceId": "synthetic-workspace"}"#;
const ASCII_DIGEST: &str = "5c8cd79f2b097a9acc262c92ff159be7d12c4d41eefa9f49e15f3d09a259b4ad";
const UNICODE_DIGEST: &str = "5eb7180bb16d9d859da4127a9e1f566b4da29620c3bd9bfe8a8f7398dad1f480";

fn clock() -> DateTime<Utc> {
    "2026-09-11T12:00:00Z".parse().unwrap()
}

fn selection<'a>(id: &'a str, digest: &'a str) -> Selection<'a> {
    Selection {
        event_id: id,
        payload_sha256: digest,
        sprint_id: "PF-80-S01",
        workspace_id: "synthetic-workspace",
        task_ids: &["task-b", "task-a", "task-a"],
    }
}

fn fixture() -> Value {
    serde_json::from_str(ASCII).unwrap()
}

// Re-sign synthetic negative cases so checks beyond the immutable hash execute.
fn resign(event: &mut Value) -> String {
    event.as_object_mut().unwrap().remove("id");
    event["id"] = json!(format!("cc-{}", digest(event)));
    digest(&json!({"event": event}))
}

fn validate(mut event: Value, now: DateTime<Utc>) -> Result<Preparation, PreparationError> {
    let hash = resign(&mut event);
    prepare(
        &event.to_string(),
        selection(event["id"].as_str().unwrap(), &hash),
        now,
    )
}

#[test]
fn delivery_goal_python_goldens_preserve_entire_payload() {
    for (source, expected_hash) in [(ASCII, ASCII_DIGEST), (UNICODE, UNICODE_DIGEST)] {
        let event: Value = serde_json::from_str(source).unwrap();
        let result = prepare(
            source,
            selection(event["id"].as_str().unwrap(), expected_hash),
            clock(),
        )
        .unwrap();
        assert_eq!(
            result,
            Preparation {
                payload: json!({"event": event}),
                payload_sha256: expected_hash.into(),
                blockers: vec!["live_authority_entitlement_owner_and_target_lifecycle_unverified"]
            }
        );
        assert_eq!(python_json(&result.payload()["event"]), source);
    }
}

#[test]
fn delivery_goal_exact_selection_and_full_digest_required() {
    let event = fixture();
    let id = event["id"].as_str().unwrap();
    for wrong in [
        "",
        "../event",
        "cc-",
        "cc-é",
        "cc-0000000000000000000000000000000000000000000000000000000000000000",
    ] {
        assert_eq!(
            prepare(ASCII, selection(wrong, ASCII_DIGEST), clock()),
            Err(PreparationError::Identity)
        );
    }
    for wrong in ["", &id[3..], UNICODE_DIGEST] {
        assert_eq!(
            prepare(ASCII, selection(id, wrong), clock()),
            Err(PreparationError::PayloadDigest)
        );
    }
    assert_eq!(
        prepare(
            &ASCII.replace("Recovery", "Changed"),
            selection(id, ASCII_DIGEST),
            clock()
        ),
        Err(PreparationError::Identity)
    );
}

#[test]
fn delivery_goal_rejects_unknown_missing_duplicate_and_wrong_types() {
    for (pointer, replacement) in [
        ("/raw", json!("private")),
        ("/goal/raw", json!(1)),
        ("/repository/remote", json!("https://example.com")),
        ("/sequence", json!(true)),
        ("/sequence", json!(0.0)),
        ("/sequence", json!(-1)),
        ("/goal/active", json!("true")),
        ("/taskIds", json!(null)),
    ] {
        let mut event = fixture();
        let (parent, key) = pointer.rsplit_once('/').unwrap();
        event.pointer_mut(parent).unwrap()[key] = replacement;
        assert_eq!(
            validate(event, clock()),
            Err(PreparationError::Schema),
            "{pointer}"
        );
    }
    let mut missing = fixture();
    missing.as_object_mut().unwrap().remove("coverage");
    assert_eq!(validate(missing, clock()), Err(PreparationError::Schema));
    let duplicate = ASCII.replacen("\"sequence\": 0", "\"sequence\": 0, \"sequence\": 0", 1);
    assert_eq!(
        prepare(&duplicate, selection("unused", ASCII_DIGEST), clock()),
        Err(PreparationError::Schema)
    );
}

#[test]
fn delivery_goal_rejects_invalid_schema_metadata_and_tasks() {
    for (pointer, replacement) in [
        ("/kind", json!("agent_output")),
        ("/instanceId", json!("other")),
        ("/sequence", json!(9007199254740992_u64)),
        ("/turnId", json!("PF-800-S01")),
        ("/goal/id", json!("PF-79-S01")),
        ("/goal/status", json!("accepted")),
        ("/repository/commit", json!("HEAD")),
        ("/repository/label", json!("other")),
        ("/coverage", json!("accepted")),
        ("/sessionId", json!("../secret")),
        ("/taskIds", json!([])),
        ("/taskIds", json!(["task-b", "task-a"])),
        ("/taskIds", json!(["task-a", "task-a"])),
        ("/taskIds", json!(["bad/task"])),
    ] {
        let mut event = fixture();
        *event.pointer_mut(pointer).unwrap() = replacement;
        assert_eq!(
            validate(event, clock()),
            Err(PreparationError::Schema),
            "{pointer}"
        );
    }
    let mut maximum = fixture();
    maximum["sequence"] = json!(9007199254740991_u64);
    assert!(validate(maximum, clock()).is_ok());
}

#[test]
fn delivery_goal_mapping_and_ambiguous_history_reject_without_retargeting() {
    for (pointer, replacement) in [("/workspaceId", "another"), ("/taskIds/0", "another")] {
        let mut event = fixture();
        *event.pointer_mut(pointer).unwrap() = json!(replacement);
        assert_eq!(validate(event, clock()), Err(PreparationError::Mapping));
    }
    let mut event = fixture();
    event["turnId"] = json!("PF-76-S01");
    event["goal"]["id"] = json!("PF-76-S01");
    assert_eq!(
        validate(event, clock()),
        Err(PreparationError::HistoricalSource)
    );
    let event = fixture();
    let mut expected = selection(event["id"].as_str().unwrap(), ASCII_DIGEST);
    expected.sprint_id = "PF-79-S01";
    assert_eq!(
        prepare(ASCII, expected, clock()),
        Err(PreparationError::Mapping)
    );
}

#[test]
fn delivery_goal_utf8_and_character_boundaries() {
    for (pointer, text, allowed) in [
        ("/repository/branch", "a".repeat(300), true),
        ("/repository/branch", "a".repeat(301), false),
        ("/repository/branch", "猫".repeat(166) + "ab", true),
        ("/repository/branch", "猫".repeat(167), false),
        ("/content", "a".repeat(2000), true),
        ("/content", "a".repeat(2001), false),
        ("/content", "😀".repeat(512), true),
        ("/content", "😀".repeat(512) + "a", false),
    ] {
        let mut event = fixture();
        *event.pointer_mut(pointer).unwrap() = json!(text);
        assert_eq!(validate(event, clock()).is_ok(), allowed, "{pointer}");
    }
}

#[test]
fn delivery_goal_secret_and_control_text_is_held() {
    for text in [
        "password=synthetic",
        "API_KEY: synthetic",
        "APİ_KEY=synthetic",
        "ſecret=x",
        "access-token = synthetic",
        "refresh token: x",
        "Bearer\u{a0}x",
        "-----BEGIN RSA PRIVATE KEY-----",
        "sk-synthetic0000",
        "ghp_synthetic0000",
        "github_pat_synthetic0000",
        "bad\u{1b}control",
        "bad\rcontrol",
    ] {
        for pointer in ["/content", "/repository/branch"] {
            let mut event = fixture();
            *event.pointer_mut(pointer).unwrap() = json!(text);
            assert_eq!(
                validate(event, clock()),
                Err(PreparationError::UnsafeText),
                "{text}"
            );
        }
    }
}

#[test]
fn delivery_goal_explicit_time_future_and_stale_boundaries() {
    assert_eq!(
        validate(
            fixture(),
            clock() - chrono::Duration::minutes(5) - chrono::Duration::nanoseconds(1)
        ),
        Err(PreparationError::Timestamp)
    );
    for timestamp in [
        "2026-09-11T12:05:00.001Z",
        "2026-09-11T12:00:00Z",
        "2026-09-11T12:00:00.000+00:00",
        "2026-02-30T12:00:00.000Z",
        "2026-09-11T12:00:60.000Z",
        "invalid",
    ] {
        let mut event = fixture();
        event["occurredAt"] = json!(timestamp);
        assert_eq!(validate(event, clock()), Err(PreparationError::Timestamp));
    }
    let mut event = fixture();
    event["occurredAt"] = json!("2026-09-11T12:05:00.000Z");
    assert!(validate(event, clock()).is_ok());
    for (milliseconds, count) in [(2_700_000, 1), (2_700_001, 2)] {
        let result = validate(
            fixture(),
            clock() + chrono::Duration::milliseconds(milliseconds),
        )
        .unwrap();
        assert_eq!(result.blockers().len(), count);
        assert_eq!(result.payload(), &json!({"event": fixture()}));
        assert_eq!(result.payload_sha256(), ASCII_DIGEST);
    }
}

#[test]
fn delivery_goal_collection_and_total_size_limits() {
    for size in [0, 33] {
        let mut event = fixture();
        event["taskIds"] = json!(
            (0..size)
                .map(|i| format!("task-{i:02}"))
                .collect::<Vec<_>>()
        );
        assert_eq!(validate(event, clock()), Err(PreparationError::Schema));
    }
    let mut event = fixture();
    event["sessionId"] = json!("a".repeat(201));
    assert_eq!(validate(event, clock()), Err(PreparationError::Schema));
    let mut event = fixture();
    event["taskIds"] = json!(
        (0..32)
            .map(|i| format!("{i:02}{}", "a".repeat(198)))
            .collect::<Vec<_>>()
    );
    event["content"] = json!("😀".repeat(512));
    let hash = resign(&mut event);
    let tasks = event["taskIds"]
        .as_array()
        .unwrap()
        .iter()
        .map(|id| id.as_str().unwrap())
        .collect::<Vec<_>>();
    let mut expected = selection(event["id"].as_str().unwrap(), &hash);
    expected.task_ids = &tasks;
    assert_eq!(
        prepare(&event.to_string(), expected, clock()),
        Err(PreparationError::UnsafeText)
    );
    assert_eq!(
        prepare(
            &" ".repeat(1024 * 1024 + 1),
            selection("unused", ASCII_DIGEST),
            clock()
        ),
        Err(PreparationError::Schema)
    );
}
