use super::*;
use crate::runtime::test_support::test_thread_metadata;
use pretty_assertions::assert_eq;
use serde_json::json;

#[path = "accounting_retention_test_support.rs"]
mod support;
use support::*;
#[path = "accounting_retention_atomic_test_support.rs"]
mod atomic_support;
use atomic_support::*;

fn owner(id: u128) -> ThreadId {
    ThreadId::from_string(&Uuid::from_u128(id).to_string()).unwrap()
}

fn owned(id: u128, time: i64, thread: u128) -> Attempt {
    let mut a = attempt(id, time);
    a.thread_id = owner(thread);
    a
}

// Every column, including future native metadata columns, in one held read snapshot.
async fn whole(conn: &mut SqliteConnection) -> anyhow::Result<Vec<Vec<String>>> {
    let mut result = Vec::new();
    for table in [
        "draft_accounting_attempts",
        "draft_accounting_observations",
        "draft_accounting_price_snapshots",
        "draft_accounting_price_bindings",
        "draft_accounting_estimates",
        "draft_accounting_contributions",
        "draft_accounting_tombstones",
        "draft_accounting_compact_days",
        "draft_accounting_compact_snapshots",
        "draft_accounting_retention_checkpoint",
        "threads",
        "thread_spawn_edges",
        "thread_dynamic_tools",
    ] {
        let columns: Vec<String> =
            sqlx::query_scalar("SELECT name FROM pragma_table_info(?) ORDER BY cid")
                .bind(table)
                .fetch_all(&mut *conn)
                .await?;
        if columns.is_empty() {
            result.push(vec!["<absent>".into()]);
            continue;
        }
        let columns = columns
            .iter()
            .map(|name| format!("\"{name}\""))
            .collect::<Vec<_>>()
            .join(",");
        result.push(
            sqlx::query_scalar(sqlx::AssertSqlSafe(format!(
                "SELECT json_array({columns}) FROM {table} ORDER BY 1"
            )))
            .fetch_all(&mut *conn)
            .await?,
        );
    }
    Ok(result)
}

async fn rows(runtime: &StateRuntime) -> anyhow::Result<Vec<Vec<String>>> {
    let mut tx = runtime.pool.begin().await?;
    let result = whole(&mut tx).await?;
    tx.commit().await?;
    Ok(result)
}

async fn reopen_twice(path: &std::path::Path, expected: &[Vec<String>]) -> anyhow::Result<()> {
    for _ in 0..2 {
        let runtime =
            StateRuntime::init_for_testing(path.to_path_buf(), "synthetic".into()).await?;
        assert_eq!(rows(&runtime).await?, expected);
        runtime.close().await;
        assert!(runtime.pool.is_closed());
    }
    Ok(())
}

async fn seed_native(runtime: &StateRuntime, path: &std::path::Path) -> anyhow::Result<()> {
    for id in [7, 8] {
        runtime
            .upsert_thread(&test_thread_metadata(path, owner(id), path.to_path_buf()))
            .await?;
        sqlx::query("INSERT INTO thread_dynamic_tools (thread_id, position, name, description, input_schema) VALUES (?, 0, 'fixture', 'synthetic', '{}')")
            .bind(owner(id).to_string()).execute(runtime.pool.as_ref()).await?;
    }
    runtime
        .upsert_thread_spawn_edge(
            owner(7),
            owner(8),
            crate::DirectionalThreadSpawnEdgeStatus::Closed,
        )
        .await?;
    Ok(())
}

async fn seed(runtime: &StateRuntime, path: &std::path::Path) -> anyhow::Result<()> {
    seed_native(runtime, path).await?;
    let store = install(runtime).await?;
    for a in [
        attempt(1, 0),
        attempt(2, DETAIL_MS - 1),
        owned(3, DETAIL_MS - 1, 8),
    ] {
        save(&store, &a, &[snapshot()]).await?;
    }
    store.maintain_retention(DETAIL_MS - 1).await
}

// Explicit case expectations; only untouched rows are copied, never generated by C2.
fn deleted(baseline: &[Vec<String>], ids: &[u128], time: i64) -> anyhow::Result<Vec<Vec<String>>> {
    let all = ids.contains(&8);
    let removed = if all { vec![1, 2, 3] } else { vec![1, 2] };
    let mut tombstones = vec![(1, REPLAY_MS), (2, DETAIL_MS - 1 + REPLAY_MS)];
    if all {
        tombstones.push((3, DETAIL_MS - 1 + REPLAY_MS));
    }
    let mut result = retained_rows(
        baseline,
        &removed,
        &[],
        &tombstones,
        if all { &[] } else { &[1000] },
        time,
    )?;
    for index in [10, 12] {
        result[index].retain(|row| {
            let row: serde_json::Value = serde_json::from_str(row).unwrap();
            !ids.iter().any(|id| row[0] == owner(*id).to_string())
        });
    }
    result[11].clear();
    Ok(result)
}

#[tokio::test]
async fn native_admission_owner_replay_and_archived_rows() -> anyhow::Result<()> {
    let home = home();
    let runtime = StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
    seed_native(&runtime, &home).await?;
    install(&runtime).await?.maintain_retention(0).await?;
    let journal = Journal { runtime: &runtime };
    for a in [attempt(1, 0), owned(2, 0, 8)] {
        journal
            .append_native(a.thread_id, &a, &[row(&a, 1, 1)], 0)
            .await?;
        let before = rows(&runtime).await?;
        journal
            .append_native(a.thread_id, &a, &[row(&a, 1, 1)], 0)
            .await?;
        assert_eq!(rows(&runtime).await?, before);
    }
    assert_eq!(
        journal.read_observations(attempt(1, 0).attempt_id).await?,
        Some((attempt(1, 0), vec![row(&attempt(1, 0), 1, 1)]))
    );
    assert_eq!(
        runtime.list_thread_spawn_descendants(owner(7)).await?,
        vec![owner(8)]
    );
    let before = rows(&runtime).await?;
    for (expected_owner, a, marker) in [
        (owner(8), attempt(3, 1), "native owner mismatch"),
        (owner(9), owned(4, 1, 9), "native owner missing"),
    ] {
        assert_error(
            journal
                .append_native(expected_owner, &a, &[], 1)
                .await
                .unwrap_err(),
            marker,
        );
        assert_eq!(rows(&runtime).await?, before);
    }
    let mut metadata = runtime.get_thread(owner(8)).await?.unwrap();
    metadata.archived_at = chrono::DateTime::from_timestamp(1_700_000_001, 0);
    runtime.upsert_thread(&metadata).await?;
    let archived = rows(&runtime).await?;
    journal
        .append_native(owner(8), &owned(5, 1, 8), &[], 1)
        .await?;
    assert_eq!(
        runtime.get_thread(owner(8)).await?.unwrap().archived_at,
        metadata.archived_at
    );
    assert_eq!(&rows(&runtime).await?[10..], &archived[10..]);
    assert_eq!(runtime.delete_threads_at(&[owner(7)], 1).await?, 1);
    let before = rows(&runtime).await?;
    for a in [attempt(1, 0), attempt(6, 1)] {
        assert_error(
            journal
                .append_native(owner(7), &a, &[], 1)
                .await
                .unwrap_err(),
            "native owner missing",
        );
        assert_eq!(rows(&runtime).await?, before);
    }
    runtime.close().await;
    reopen_twice(&home, &before).await
}

#[tokio::test]
async fn native_raw_compact_missing_counts_and_shared_price_survive_reopens() -> anyhow::Result<()>
{
    for (compact_only, missing) in [(false, false), (true, false), (true, true)] {
        let home = home();
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        seed(&runtime, &home).await?;
        let time = if compact_only {
            2 * DETAIL_MS - 1
        } else {
            DETAIL_MS
        };
        attach(&runtime).maintain_retention(time).await?;
        if compact_only {
            assert!(rows(&runtime).await?[0].is_empty());
        }
        if missing {
            // A missing native row must not strand its existing compact ownership.
            sqlx::query("DELETE FROM threads WHERE id = ?")
                .bind(owner(7).to_string())
                .execute(runtime.pool.as_ref())
                .await?;
        }
        let baseline = rows(&runtime).await?;
        runtime.close().await;
        reopen_twice(&home, &baseline).await?;
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        assert_eq!(
            runtime.delete_threads_at(&[owner(7)], time).await?,
            u64::from(!missing)
        );
        let mut expected = deleted(&baseline, &[7], time)?;
        if compact_only {
            // The other owner's independently retained compact day and provenance survive.
            expected[6] = baseline[6].clone();
            for index in [7, 8] {
                expected[index] = baseline[index]
                    .iter()
                    .filter(|row| {
                        serde_json::from_str::<serde_json::Value>(row).unwrap()[0]
                            == owner(8).to_string()
                    })
                    .cloned()
                    .collect();
            }
        }
        assert_eq!(rows(&runtime).await?, expected);
        assert_eq!(
            runtime
                .delete_threads_at(&[owner(7), owner(99)], time)
                .await?,
            0
        );
        assert_eq!(rows(&runtime).await?, expected);
        assert_eq!(
            attach(&runtime)
                .read_retained_day(owner(8), 89, time)
                .await?,
            RetainedDay::Available {
                coverage: RetentionCoverage {
                    completed_as_of_ms: time,
                    detail_expired_through_ms: Some(time - DETAIL_MS),
                    aggregate_day_floor: 0,
                    oldest_recorded_day: Some(89)
                },
                totals: Current::Ready(
                    values(
                        [0, 1, 0, 0, 0, 0, 0],
                        [1, 0, 1, 1, 1, 1, 1],
                        "0.000000000000000000000001",
                        1,
                        1
                    )
                    .to_day_totals()?
                ),
            }
        );
        runtime.close().await;
        reopen_twice(&home, &expected).await?;
    }
    Ok(())
}

#[tokio::test]
async fn native_post_accounting_faults_and_second_owner_rollback_retry() -> anyhow::Result<()> {
    for (site, event, predicate) in [
        (
            "second_owner",
            "DELETE ON draft_accounting_attempts",
            "OLD.attempt_id = '00000000-0000-0000-0000-000000000003'",
        ),
        ("tools", "DELETE ON thread_dynamic_tools", "1"),
        ("edges", "DELETE ON thread_spawn_edges", "1"),
        ("threads", "DELETE ON threads", "1"),
    ] {
        let home = home();
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        seed(&runtime, &home).await?;
        let baseline = rows(&runtime).await?;
        let predicate = format!(
            "({predicate}) AND NOT EXISTS(SELECT 1 FROM draft_accounting_attempts WHERE attempt_id = '00000000-0000-0000-0000-000000000002') AND (SELECT completed_as_of_ms FROM draft_accounting_retention_checkpoint) = {DETAIL_MS}"
        );
        fault(&mut *runtime.pool.acquire().await?, site, event, &predicate).await?;
        assert_error(
            runtime
                .delete_threads_at(&[owner(7), owner(8)], DETAIL_MS)
                .await
                .unwrap_err(),
            &format!("retention_fault_{site}"),
        );
        assert_eq!(rows(&runtime).await?, baseline);
        assert_eq!(
            runtime.list_thread_spawn_descendants(owner(7)).await?,
            vec![owner(8)]
        );
        runtime.close().await;
        reopen_twice(&home, &baseline).await?;
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        sqlx::query(sqlx::AssertSqlSafe(format!(
            "DROP TRIGGER retention_fault_{site}"
        )))
        .execute(runtime.pool.as_ref())
        .await?;
        assert_eq!(
            runtime
                .delete_threads_at(&[owner(7), owner(8)], DETAIL_MS)
                .await?,
            2
        );
        let expected = deleted(&baseline, &[7, 8], DETAIL_MS)?;
        assert_eq!(rows(&runtime).await?, expected);
        assert_eq!(
            runtime
                .delete_threads_at(&[owner(7), owner(8)], DETAIL_MS)
                .await?,
            0
        );
        assert_eq!(rows(&runtime).await?, expected);
        runtime.close().await;
        reopen_twice(&home, &expected).await?;
    }
    Ok(())
}

#[tokio::test]
async fn native_commit_foreign_key_failure_is_jointly_atomic() -> anyhow::Result<()> {
    let home = home();
    let runtime = StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
    seed(&runtime, &home).await?;
    let baseline = rows(&runtime).await?;
    sqlx::raw_sql("CREATE TRIGGER native_commit_fault AFTER DELETE ON threads BEGIN INSERT INTO draft_accounting_compact_snapshots VALUES ('orphan', 0, 'missing'); END;")
        .execute(runtime.pool.as_ref()).await?;
    let other = peer(&runtime).await?;
    sqlx::query("PRAGMA defer_foreign_keys=ON")
        .execute(other.pool.as_ref())
        .await?;
    let error = other
        .delete_threads_at(&[owner(7)], DETAIL_MS)
        .await
        .unwrap_err();
    assert_eq!(
        error
            .downcast_ref::<sqlx::Error>()
            .unwrap()
            .as_database_error()
            .unwrap()
            .code()
            .as_deref(),
        Some("787")
    );
    assert_error(error, "FOREIGN KEY constraint failed");
    assert_eq!(rows(&other).await?, baseline);
    other.pool.close().await;
    runtime.close().await;
    reopen_twice(&home, &baseline).await?;
    let runtime = StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
    sqlx::query("DROP TRIGGER native_commit_fault")
        .execute(runtime.pool.as_ref())
        .await?;
    assert_eq!(runtime.delete_threads_at(&[owner(7)], DETAIL_MS).await?, 1);
    let expected = deleted(&baseline, &[7], DETAIL_MS)?;
    assert_eq!(rows(&runtime).await?, expected);
    runtime.close().await;
    reopen_twice(&home, &expected).await
}

#[tokio::test]
async fn native_two_real_writer_orders_and_joint_read_snapshots() -> anyhow::Result<()> {
    for append_first in [true, false] {
        let home = home();
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        seed(&runtime, &home).await?;
        let baseline = rows(&runtime).await?;
        let other = peer(&runtime).await?;
        let mut reader = runtime.pool.begin().await?;
        assert_eq!(whole(&mut reader).await?, baseline);
        let (held_tx, held_rx) = tokio::sync::oneshot::channel();
        let (release_tx, release_rx) = tokio::sync::oneshot::channel();
        let pool = runtime.pool.clone();
        let holder = tokio::spawn(async move {
            let mut tx = pool.begin_with("BEGIN IMMEDIATE").await?;
            if append_first {
                let a = attempt(2, DETAIL_MS - 1);
                Journal::append_native_on_connection(
                    &mut tx,
                    owner(7),
                    &a,
                    &[row(&a, 2, 2)],
                    DETAIL_MS,
                )
                .await?;
            } else {
                assert_eq!(
                    StateRuntime::delete_threads_on_connection(&mut tx, &[owner(7)], DETAIL_MS)
                        .await?,
                    1
                );
            }
            held_tx.send(()).unwrap();
            release_rx.await?;
            tx.commit().await?;
            anyhow::Ok(())
        });
        held_rx.await?;
        let journal = Journal { runtime: &other };
        let error = if append_first {
            other
                .delete_threads_at(&[owner(7)], DETAIL_MS)
                .await
                .unwrap_err()
        } else {
            journal
                .append_native(owner(7), &attempt(2, DETAIL_MS - 1), &[], DETAIL_MS)
                .await
                .unwrap_err()
        };
        let sql = error
            .downcast_ref::<sqlx::Error>()
            .unwrap()
            .as_database_error()
            .unwrap();
        assert!(matches!(sql.code().as_deref(), Some("5" | "6")), "{sql}");
        assert_eq!(rows(&other).await?, baseline);
        release_tx.send(()).unwrap();
        holder.await??;
        if append_first {
            // The first real append committed before the wrapper retry deletes it.
            assert_eq!(
                journal.read_observations(attempt(2, 0).attempt_id).await?,
                Some((
                    attempt(2, DETAIL_MS - 1),
                    vec![row(&attempt(2, 0), 1, 1), row(&attempt(2, 0), 2, 2)]
                ))
            );
            assert_eq!(other.delete_threads_at(&[owner(7)], DETAIL_MS).await?, 1);
        }
        let expected = deleted(&baseline, &[7], DETAIL_MS)?;
        for a in [attempt(2, DETAIL_MS - 1), attempt(99, DETAIL_MS)] {
            assert_error(
                journal
                    .append_native(owner(7), &a, &[], DETAIL_MS)
                    .await
                    .unwrap_err(),
                "native owner missing",
            );
            assert_eq!(rows(&other).await?, expected);
        }
        assert_eq!(whole(&mut reader).await?, baseline);
        reader.commit().await?;
        assert_eq!(rows(&runtime).await?, expected);
        other.pool.close().await;
        runtime.close().await;
        reopen_twice(&home, &expected).await?;
    }
    Ok(())
}

#[tokio::test]
async fn native_invalid_time_activation_and_late_import_roll_back() -> anyhow::Result<()> {
    let home = home();
    let runtime = StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
    seed(&runtime, &home).await?;
    let baseline = rows(&runtime).await?;
    let journal = Journal { runtime: &runtime };
    for (time, marker) in [(-1, "negative"), (DETAIL_MS - 2, "backward")] {
        assert_error(
            journal
                .append_native(owner(7), &attempt(2, DETAIL_MS - 1), &[], time)
                .await
                .unwrap_err(),
            marker,
        );
        assert_error(
            runtime
                .delete_threads_at(&[owner(7)], time)
                .await
                .unwrap_err(),
            marker,
        );
        assert_eq!(rows(&runtime).await?, baseline);
    }
    for (a, batch, marker) in [
        (attempt(99, 0), vec![], "unsupported compact-only"),
        (attempt(99, DETAIL_MS + 1), vec![], "future dispatch"),
        (
            attempt(2, DETAIL_MS - 1),
            vec![row(&attempt(2, 0), 1, 99)],
            "observation conflict",
        ),
    ] {
        assert_error(
            journal
                .append_native(owner(7), &a, &batch, DETAIL_MS)
                .await
                .unwrap_err(),
            marker,
        );
        // These failures occur after maintenance would have compacted attempt1.
        assert_eq!(rows(&runtime).await?, baseline);
    }
    for (sql, marker) in [
        (
            "UPDATE draft_accounting_retention_checkpoint SET admission_active = 0",
            "requires active",
        ),
        (
            "UPDATE draft_accounting_retention_checkpoint SET admission_active = 1, completed_as_of_ms = NULL",
            "active NULL",
        ),
        (
            "DROP TABLE draft_accounting_compact_snapshots",
            "partial retention schema",
        ),
    ] {
        sqlx::query(sql).execute(runtime.pool.as_ref()).await?;
        let invalid = rows(&runtime).await?;
        assert_error(
            journal
                .append_native(owner(7), &attempt(99, DETAIL_MS), &[], DETAIL_MS)
                .await
                .unwrap_err(),
            marker,
        );
        assert_error(
            runtime
                .delete_threads_at(&[owner(7)], DETAIL_MS)
                .await
                .unwrap_err(),
            marker,
        );
        assert_eq!(rows(&runtime).await?, invalid);
    }
    let invalid = rows(&runtime).await?;
    runtime.close().await;
    reopen_twice(&home, &invalid).await
}

#[tokio::test]
async fn public_delete_wrapper_and_absent_schema_keep_native_contract() -> anyhow::Result<()> {
    for accounting in [false, true] {
        let home = home();
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        assert_eq!(
            sqlx::query_scalar::<_, i64>(
                "SELECT count(*) FROM sqlite_schema WHERE name GLOB 'draft_accounting_*'"
            )
            .fetch_one(runtime.pool.as_ref())
            .await?,
            0
        );
        seed_native(&runtime, &home).await?;
        let now = chrono::Utc::now().timestamp_millis();
        if accounting {
            install(&runtime).await?.maintain_retention(now).await?;
            let a = attempt(1, now);
            Journal { runtime: &runtime }
                .append_native(owner(7), &a, &[], now)
                .await?;
        }
        assert_eq!(runtime.delete_threads_strict(&[]).await?, 0);
        assert_eq!(runtime.delete_thread(owner(7)).await?, 1);
        assert_eq!(runtime.delete_thread(owner(7)).await?, 0);
        let after = rows(&runtime).await?;
        assert_eq!(after[10].len(), 1);
        assert!(after[11].is_empty());
        assert_eq!(after[12].len(), 1);
        if accounting {
            assert!(after[0].is_empty());
            assert_eq!(
                after[6],
                vec![json!([Uuid::from_u128(1), now + REPLAY_MS]).to_string()]
            );
            let checkpoint: i64 = sqlx::query_scalar(
                "SELECT completed_as_of_ms FROM draft_accounting_retention_checkpoint",
            )
            .fetch_one(runtime.pool.as_ref())
            .await?;
            assert!((now..=chrono::Utc::now().timestamp_millis()).contains(&checkpoint));
        } else {
            assert_eq!(&after[..10], &vec![vec!["<absent>".to_string()]; 10]);
            assert_eq!(runtime.delete_threads_at(&[owner(99)], -1).await?, 0);
            assert_eq!(rows(&runtime).await?, after);
        }
        runtime.close().await;
        reopen_twice(&home, &after).await?;
    }
    Ok(())
}

#[tokio::test]
async fn separate_store_failures_preserve_retry_graph_without_global_rollback_claim()
-> anyhow::Result<()> {
    for site in ["logs", "memory", "goals", "native"] {
        let home = home();
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        seed(&runtime, &home).await?;
        let memory = sqlx::sqlite::SqlitePoolOptions::new()
            .max_connections(1)
            .connect_with(
                sqlx::sqlite::SqliteConnectOptions::new()
                    .filename(runtime.sqlite.memories_db_path()),
            )
            .await?;
        let goals = sqlx::sqlite::SqlitePoolOptions::new()
            .max_connections(1)
            .connect_with(
                sqlx::sqlite::SqliteConnectOptions::new().filename(runtime.sqlite.goals_db_path()),
            )
            .await?;
        sqlx::query("INSERT INTO logs (ts, ts_nanos, level, target, feedback_log_body, thread_id) VALUES (1, 0, 'INFO', 'synthetic', 'fixture', ?)")
            .bind(owner(7).to_string()).execute(runtime.logs_pool.as_ref()).await?;
        sqlx::query("INSERT INTO stage1_outputs (thread_id, source_updated_at, raw_memory, rollout_summary, generated_at) VALUES (?, 1, 'synthetic', 'synthetic', 1)")
            .bind(owner(7).to_string()).execute(&memory).await?;
        runtime
            .thread_goals()
            .replace_thread_goal(
                owner(7),
                "synthetic",
                crate::ThreadGoalStatus::Active,
                /*token_budget*/ None,
            )
            .await?;
        let (pool, table) = match site {
            "logs" => (runtime.logs_pool.as_ref(), "logs"),
            "memory" => (&memory, "stage1_outputs"),
            "goals" => (&goals, "thread_goals"),
            "native" => (runtime.pool.as_ref(), "threads"),
            _ => unreachable!(),
        };
        fault(
            &mut *pool.acquire().await?,
            site,
            &format!("DELETE ON {table}"),
            "1",
        )
        .await?;
        let baseline = rows(&runtime).await?;
        assert_error(
            runtime
                .delete_threads_at(&[owner(7)], DETAIL_MS)
                .await
                .unwrap_err(),
            &format!("retention_fault_{site}"),
        );
        assert_eq!(rows(&runtime).await?, baseline);
        assert_eq!(
            runtime.list_thread_spawn_descendants(owner(7)).await?,
            vec![owner(8)]
        );
        let counts = (
            sqlx::query_scalar::<_, i64>("SELECT count(*) FROM logs")
                .fetch_one(runtime.logs_pool.as_ref())
                .await?,
            sqlx::query_scalar::<_, i64>("SELECT count(*) FROM stage1_outputs")
                .fetch_one(&memory)
                .await?,
            sqlx::query_scalar::<_, i64>("SELECT count(*) FROM thread_goals")
                .fetch_one(&goals)
                .await?,
        );
        assert_eq!(
            counts,
            match site {
                "logs" => (1, 1, 1),
                "memory" => (0, 1, 1),
                "goals" => (0, 0, 1),
                "native" => (0, 0, 0),
                _ => unreachable!(),
            }
        );
        sqlx::query(sqlx::AssertSqlSafe(format!(
            "DROP TRIGGER retention_fault_{site}"
        )))
        .execute(pool)
        .await?;
        memory.close().await;
        goals.close().await;
        runtime.close().await;
        reopen_twice(&home, &baseline).await?;
        let runtime =
            StateRuntime::init_for_testing(home.to_path_buf(), "synthetic".into()).await?;
        assert_eq!(runtime.delete_threads_at(&[owner(7)], DETAIL_MS).await?, 1);
        let expected = deleted(&baseline, &[7], DETAIL_MS)?;
        assert_eq!(rows(&runtime).await?, expected);
        runtime.close().await;
        reopen_twice(&home, &expected).await?;
    }
    Ok(())
}
