// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType";

export type Account = { "type": "apiKey",
/**
 * The environment variable the key is read from (for example
 * `OPENAI_API_KEY`), or `null` for a saved key.
 */
envVar: string | null, } | { "type": "chatgpt", email: string | null, planType: PlanType, } | { "type": "amazonBedrock", usesCodexManagedCredentials: boolean, };
