// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionPolicy } from "./RetentionPolicy";

export type AgentClass = { "class": "crew_member", crew_id: string, logical_member_id: string, human_addressable: boolean, } | { "class": "ephemeral_task", assignment_id: string, retention: RetentionPolicy, };
