// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRecordSentModelRequestResponse = {
/**
 * False when the server is not collecting, or does not recognise the
 * route. Never an error: reporting spend must not fail the work.
 */
recorded: boolean, };
