// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";
import type { RuntimeSelectionSource } from "../RuntimeSelectionSource";

/**
 * Authoritative route currently configured for a loaded thread.
 *
 * Stored threads created by older releases may omit this field. Clients must treat an absent
 * route as unavailable identity evidence rather than inheriting or guessing from the viewer.
 */
export type ThreadRuntimeRoute = { modelProvider: string, model: string, reasoningEffort: ReasoningEffort | null, serviceTier: string | null,
/**
 * Why the thread received this route when it was created.
 * Legacy and non-spawned threads omit this value.
 */
selectionSource: RuntimeSelectionSource | null, };
