// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * One model request a client sent itself, reported so the operator's ledger
 * can record spend this process never saw.
 *
 * The Claude panes bridge is the caller: it posts to a provider from inside
 * the TUI, which does not run the model client. Only routes the server
 * recognises are recorded.
 */
export type ThreadRecordSentModelRequestParams = { threadId: string,
/**
 * The account the client believes it billed. Recorded only when the
 * server knows this provider and the route below is its own.
 */
providerId: string,
/**
 * The base URL the request went to, and the endpoint underneath it.
 */
baseUrl: string, path: string, model: string,
/**
 * The `usage` object the provider's response carried, if it carried one.
 */
usage?: JsonValue | null, };
