// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API rates for a whole request whose input exceeds a published threshold,
 * such as OpenAI's long-context price for prompts above 272K input tokens.
 */
export type LongContextRates = {
/**
 * The rates apply when the request's input tokens (cached and cache
 * writes included) are strictly more than this.
 */
above_input_tokens: number, input_milli_usd_per_million_tokens: number, output_milli_usd_per_million_tokens: number, cached_input_milli_usd_per_million_tokens?: number, cache_write_milli_usd_per_million_tokens?: number, };
