// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-token API rates, in milli-USD per million tokens.
 */
export type MeteredRates = { input_milli_usd_per_million_tokens: number, output_milli_usd_per_million_tokens: number, cached_input_milli_usd_per_million_tokens: number | null, };
