// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelBilling } from "./ModelBilling";
import type { ModelCapabilityTier } from "./ModelCapabilityTier";

/**
 * Canonical spawn-allocation metadata carried with a model through every catalogue layer.
 */
export type ModelOrchestrationMetadata = { "status": "eligible", provider_id: string, capability: ModelCapabilityTier, billing: ModelBilling, } | { "status": "disabled", provider_id: string, capability: ModelCapabilityTier, reason: string, };
