// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeekdaySet } from "./WeekdaySet";

/**
 * Billing data for an exact provider/model route.
 *
 * Monetary values use milli-USD per million tokens so catalogue metadata remains exact,
 * serializable, and equality-comparable without floating point.
 */
export type ModelBilling = { "kind": "plan",
/**
 * Relative subscription-pool burn where 1000 means 1.0x.
 */
relative_burn_millis: number, } | { "kind": "plan_schedule",
/**
 * Normal off-peak relative burn where 1000 means 1.0x.
 */
off_peak_relative_burn_millis: number,
/**
 * Peak relative burn where 1000 means 1.0x.
 */
peak_relative_burn_millis: number,
/**
 * Inclusive peak-window start, expressed as an hour in UTC.
 */
peak_start_utc_hour: number,
/**
 * Exclusive peak-window end, expressed as an hour in UTC.
 */
peak_end_utc_hour: number,
/**
 * UTC weekdays on which the peak window applies. Omitted means every day for backward
 * compatibility with older catalogue entries.
 */
peak_weekdays: WeekdaySet | null, promotional_off_peak_relative_burn_millis: number | null, promotion_valid_through_utc: string | null, } | { "kind": "metered", input_milli_usd_per_million_tokens: number, output_milli_usd_per_million_tokens: number, cached_input_milli_usd_per_million_tokens: number | null, } | { "kind": "auth_dependent", plan_relative_burn_millis: number, api_key_input_milli_usd_per_million_tokens: number, api_key_output_milli_usd_per_million_tokens: number, api_key_cached_input_milli_usd_per_million_tokens: number | null, } | { "kind": "local" };
