// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LongContextRates } from "./LongContextRates";
import type { MeteredRates } from "./MeteredRates";
import type { UtcHourWindow } from "./UtcHourWindow";
import type { WeekdaySet } from "./WeekdaySet";

/**
 * Billing data for an exact provider/model route.
 *
 * Monetary values use milli-USD per million tokens so catalogue metadata remains exact,
 * serializable, and equality-comparable without floating point.
 */
export type ModelBilling = { "kind": "plan",
/**
 * Relative subscription-pool burn where 1000 means 1.0x.
 */
relative_burn_millis: number, } | { "kind": "plan_schedule",
/**
 * Normal off-peak relative burn where 1000 means 1.0x.
 */
off_peak_relative_burn_millis: number,
/**
 * Peak relative burn where 1000 means 1.0x.
 */
peak_relative_burn_millis: number,
/**
 * Inclusive peak-window start, expressed as an hour in UTC.
 */
peak_start_utc_hour: number,
/**
 * Exclusive peak-window end, expressed as an hour in UTC.
 */
peak_end_utc_hour: number,
/**
 * UTC weekdays on which the peak window applies. Omitted means every day for backward
 * compatibility with older catalogue entries.
 */
peak_weekdays: WeekdaySet | null, promotional_off_peak_relative_burn_millis: number | null, promotion_valid_through_utc: string | null, } | { "kind": "metered", input_milli_usd_per_million_tokens: number, output_milli_usd_per_million_tokens: number, cached_input_milli_usd_per_million_tokens: number | null,
/**
 * The published cache-write price. Omitted means the catalogue states
 * none, not that writes are free.
 */
cache_write_milli_usd_per_million_tokens?: number,
/**
 * Rates for a request whose input exceeds a published threshold.
 */
long_context?: LongContextRates,
/**
 * The last UTC instant (RFC 3339) the provider says these rates hold,
 * such as the end of a promotion. Afterwards the row states no price.
 */
valid_through_utc?: string, } | { "kind": "metered_schedule", off_peak: MeteredRates, peak: MeteredRates,
/**
 * Peak windows. Outside every window the off-peak rates apply.
 */
peak_windows: Array<UtcHourWindow>,
/**
 * UTC weekdays on which the peak windows apply. Omitted means every day.
 */
peak_weekdays: WeekdaySet | null,
/**
 * UTC calendar dates (`YYYY-MM-DD`) with no peak at all, such as the
 * provider's published holidays.
 */
off_peak_dates_utc: Array<string>, } | { "kind": "auth_dependent", plan_relative_burn_millis: number, api_key_input_milli_usd_per_million_tokens: number, api_key_output_milli_usd_per_million_tokens: number, api_key_cached_input_milli_usd_per_million_tokens: number | null, api_key_cache_write_milli_usd_per_million_tokens?: number, api_key_long_context?: LongContextRates,
/**
 * As `Metered::valid_through_utc`, for the API-key side only.
 */
api_key_valid_through_utc?: string, } | { "kind": "local" };
