// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capability class used by orchestration when matching a model to spawned work.
 */
export type ModelCapabilityTier = "frontier" | "balanced" | "fast" | "legacy" | "unclassified";
