// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authoritative reason a spawned thread received its initial runtime route.
 *
 * This is persisted independently from the route itself so clients can explain
 * whether a child was explicitly pinned or selected by policy without trying
 * to infer intent from model names or the current parent configuration.
 */
export type RuntimeSelectionSource = "explicit_request" | "operator_default" | "agent_role" | "inherited_runtime";
