// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { ThreadId } from "./ThreadId";
import type { AgentClass } from "./v2/AgentClass";

export type SubAgentSource = "review" | "compact" | { "thread_spawn": { parent_thread_id: ThreadId, depth: number, agent_path: AgentPath | null, agent_nickname: string | null, agent_role: string | null,
/**
 * Product-level retention and addressing classification for this native thread.
 *
 * Older rollouts omit this field and remain resumable as unclassified agents.
 */
agent_class: AgentClass | null, } } | "memory_consolidation" | { "other": string };
