// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `[start, end)` window in whole UTC hours; it may wrap past midnight.
 */
export type UtcHourWindow = { start_utc_hour: number, end_utc_hour: number, };
