// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UTC weekdays on which a scheduled plan peak applies.
 *
 * `ModelBilling::PlanSchedule::peak_weekdays == None` retains the legacy behavior where the
 * peak window applies every day.
 */
export type WeekdaySet = { monday: boolean, tuesday: boolean, wednesday: boolean, thursday: boolean, friday: boolean, saturday: boolean, sunday: boolean, };
