use super::*;
use crate::tools::handlers::multi_agents_spec::create_interrupt_agent_tool_v2;
use crate::turn_timing::now_unix_timestamp_ms;
use codex_protocol::error::CodexErr;
use codex_protocol::models::ResponseItemMetadata;
use codex_tools::ToolSpec;

pub(crate) struct Handler;

impl ToolExecutor<ToolInvocation> for Handler {
    fn tool_name(&self) -> ToolName {
        ToolName::plain("interrupt_agent")
    }

    fn spec(&self) -> ToolSpec {
        create_interrupt_agent_tool_v2()
    }

    fn handle(&self, invocation: ToolInvocation) -> codex_tools::ToolExecutorFuture<'_> {
        Box::pin(async move {
            handle_interrupt_agent(invocation)
                .await
                .map(boxed_tool_output)
        })
    }
}

async fn handle_interrupt_agent(
    invocation: ToolInvocation,
) -> Result<InterruptAgentResult, FunctionCallError> {
    let ToolInvocation {
        session,
        turn,
        payload,
        call_id,
        ..
    } = invocation;
    ensure_manager_tool_allowed(&turn, "interrupt_agent")?;
    let arguments = function_arguments(payload)?;
    let args: InterruptAgentArgs = parse_arguments(&arguments)?;
    let reason = args.reason.trim();
    if reason.is_empty() {
        return Err(FunctionCallError::RespondToModel(
            "interrupt reason must not be empty".to_string(),
        ));
    }
    let superseding_task = args
        .superseding_task
        .map(|task| task.trim().to_string())
        .filter(|task| !task.is_empty());
    let explicit_agent_path = AgentPath::try_from(args.target.trim()).ok();
    if explicit_agent_path.as_ref().is_some_and(AgentPath::is_root) {
        return Err(FunctionCallError::RespondToModel(
            "root is not a spawned agent".to_string(),
        ));
    }
    let agent_id = resolve_agent_target(&session, &turn, &args.target).await?;
    if session.services.agent_control.is_root_thread(agent_id) {
        return Err(FunctionCallError::RespondToModel(
            "root is not a spawned agent".to_string(),
        ));
    }
    let receiver_agent = match explicit_agent_path.as_ref() {
        Some(agent_path) => session
            .services
            .agent_control
            .get_agent_metadata_for_path(agent_path)
            .filter(|metadata| metadata.agent_id == Some(agent_id))
            .ok_or_else(|| {
                FunctionCallError::RespondToModel(format!(
                    "live agent path `{agent_path}` no longer matches its resolved thread"
                ))
            })?,
        None => session
            .services
            .agent_control
            .ensure_agent_known(agent_id)
            .map_err(|err| collab_agent_error(agent_id, err))?,
    };
    if agent_id == session.thread_id {
        return Err(FunctionCallError::RespondToModel(
            "an agent cannot interrupt itself; return your result and let the parent interrupt you if needed"
                .to_string(),
        ));
    }
    let receiver_agent_path = receiver_agent.agent_path.clone().ok_or_else(|| {
        FunctionCallError::RespondToModel("target agent is missing an agent_path".to_string())
    })?;
    let status = session.services.agent_control.get_status(agent_id).await;
    let actor_path = turn
        .session_source
        .get_agent_path()
        .unwrap_or_else(AgentPath::root);
    let actor = match (
        turn.session_source.get_nickname(),
        turn.session_source.get_agent_role(),
    ) {
        (Some(nickname), Some(role)) => format!("{nickname} [{role}] · {actor_path}"),
        (Some(nickname), None) => format!("{nickname} · {actor_path}"),
        (None, _) => actor_path.to_string(),
    };
    let target = match (
        receiver_agent.agent_nickname.as_deref(),
        receiver_agent.agent_role.as_deref(),
    ) {
        (Some(nickname), Some(role)) => format!("{nickname} [{role}] · {receiver_agent_path}"),
        (Some(nickname), None) => format!("{nickname} · {receiver_agent_path}"),
        (None, _) => receiver_agent_path.to_string(),
    };
    let process_effect = "model turn aborted; active turn-owned tool processes receive SIGTERM cleanup before abort; durable unified-exec background processes are preserved and remain inspectable in /ps".to_string();
    let audit_copy = format!(
        "Actor: {actor}\nTarget: {target}\nReason: {reason}\nSuperseding task/dispatch: {}\nProcess effect: {process_effect}",
        superseding_task.as_deref().unwrap_or("none")
    );
    let result = match session
        .services
        .agent_control
        .interrupt_agent(agent_id)
        .await
    {
        Ok(_) | Err(CodexErr::ThreadNotFound(_)) | Err(CodexErr::InternalAgentDied) => Ok(()),
        Err(err) => Err(collab_agent_error(agent_id, err)),
    };
    result?;
    if status != AgentStatus::NotFound {
        // This audit copy is generated by the runtime, so it is plaintext. The encrypted
        // collaboration fields are reserved for model-produced values that have already been
        // encrypted by the Responses API. Mislabeling this string as encrypted makes the target
        // model attempt to decrypt ordinary UTF-8 and hides the control tuple behind a transport
        // error instead of rendering it in the target pane.
        let mut communication = InterAgentCommunication::new(
            actor_path,
            receiver_agent_path.clone(),
            Vec::new(),
            format!("CONTROL EVENT — INTERRUPT\n{audit_copy}"),
            /*trigger_turn*/ true,
        )
        .with_kind(codex_protocol::protocol::AgentMessageKind::ControlRequest);
        communication
            .metadata
            .get_or_insert_with(ResponseItemMetadata::default)
            .source_call_id = Some(call_id.clone());
        session
            .services
            .agent_control
            .send_inter_agent_communication(agent_id, communication)
            .await
            .map_err(|err| collab_agent_error(agent_id, err))?;
    }
    session
        .send_event(
            &turn,
            SubAgentActivityEvent {
                event_id: call_id,
                occurred_at_ms: now_unix_timestamp_ms(),
                agent_thread_id: agent_id,
                agent_path: receiver_agent_path,
                agent_nickname: receiver_agent.agent_nickname,
                agent_role: receiver_agent.agent_role,
                task_preview: Some(audit_copy),
                kind: SubAgentActivityKind::Interrupted,
            }
            .into(),
        )
        .await;

    Ok(InterruptAgentResult {
        previous_status: status,
        actor,
        target,
        reason: reason.to_string(),
        superseding_task,
        process_effect,
    })
}

impl CoreToolRuntime for Handler {
    fn matches_kind(&self, payload: &ToolPayload) -> bool {
        matches!(payload, ToolPayload::Function { .. })
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct InterruptAgentArgs {
    target: String,
    reason: String,
    superseding_task: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
pub(crate) struct InterruptAgentResult {
    pub(crate) previous_status: AgentStatus,
    actor: String,
    target: String,
    reason: String,
    superseding_task: Option<String>,
    process_effect: String,
}

impl ToolOutput for InterruptAgentResult {
    fn log_preview(&self) -> String {
        tool_output_json_text(self, "interrupt_agent")
    }

    fn success_for_logging(&self) -> bool {
        true
    }

    fn to_response_item(&self, call_id: &str, payload: &ToolPayload) -> ResponseInputItem {
        tool_output_response_item(call_id, payload, self, Some(true), "interrupt_agent")
    }

    fn code_mode_result(&self, _payload: &ToolPayload) -> JsonValue {
        tool_output_code_mode_result(self, "interrupt_agent")
    }
}
