//! Durable GPU rental control plane used by PFTerminal's `/gpu` product surface.

mod controller;
mod credential;
mod market;
mod provider;
mod provider_http;
mod readiness;
mod recipe;
mod runpod;
mod vast;

pub use controller::ControllerEvent;
pub use controller::GpuRentalController;
pub use controller::ReconcileConfig;
pub use credential::GpuCredential;
pub use credential::GpuCredentialError;
pub use credential::GpuCredentialKind;
pub use credential::GpuCredentialResolver;
pub use credential::RUNPOD_API_KEY_LABEL;
pub use credential::SecretValue;
pub use credential::VAST_API_KEY_LABEL;
pub use credential::VaultGpuCredentialResolver;
pub use market::GpuMarketService;
pub use market::RentalAuthorization;
pub use provider::BillingState;
pub use provider::CreateInstanceRequest;
pub use provider::GpuInstance;
pub use provider::GpuInstanceState;
pub use provider::GpuOffer;
pub use provider::GpuProvider;
pub use provider::HardwareRequirements;
pub use provider::OwnedInstanceQuery;
pub use provider::ProviderCapabilities;
pub use provider::ProviderError;
pub use provider::ProviderErrorKind;
pub use provider::ProviderResult;
pub use provider::SearchOffersRequest;
pub use readiness::EndpointReadinessReport;
pub use readiness::GpuEndpointProber;
pub use readiness::GpuReadinessProbe;
pub use recipe::GpuRecipe;
pub use recipe::RecipeCatalog;
pub use runpod::RunpodProvider;
pub use vast::VastProvider;
