//! Metadata-only Claude subscription authentication selection and health contracts.

use chrono::Utc;
use serde::Deserialize;
use serde::Serialize;
use sha2::Digest;
use sha2::Sha256;
use std::path::Path;
use thiserror::Error;
use unicode_normalization::UnicodeNormalization;
use zeroize::Zeroizing;

use crate::CredentialType;
use crate::Vault;
use crate::VaultError;
use codex_secrets::SecretName;
use codex_secrets::SecretScope;

const CLAUDE_AUTH_SELECTION_SECRET_NAME: &str = "CLAUDE_AUTH_SELECTION";
const CLAUDE_AUTH_SELECTION_VERSION: u32 = 1;
const MAX_SOURCE_ID_BYTES: usize = 256;
const MAX_MANAGED_TOKEN_BYTES: usize = 16 * 1024;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum EnrollmentFailurePoint {
    None,
    #[cfg(test)]
    AfterTokenWrite,
    #[cfg(test)]
    AfterIndexWrite,
}

/// Stable encrypted-vault label for Corbanu's managed Claude subscription token.
pub const MANAGED_CLAUDE_TOKEN_LABEL: &str = "provider/claude-code-oauth-token";
pub const MANAGED_CLAUDE_AUTH_SOURCE_ID: &str = "corbanu-vault:claude-plan";
pub const ENVIRONMENT_CLAUDE_AUTH_SOURCE_ID: &str = "environment:CLAUDE_CODE_OAUTH_TOKEN";
pub const MACOS_KEYCHAIN_CLAUDE_AUTH_SOURCE_ID: &str = "claude-login:macos-keychain";
pub const CREDENTIALS_FILE_CLAUDE_AUTH_SOURCE_ID: &str = "claude-login:credentials-file";

/// Match Claude Code's macOS Keychain service identity for one configuration profile.
pub fn claude_code_macos_keychain_service(
    config_dir: &Path,
    config_dir_overridden: bool,
    custom_oauth: bool,
) -> String {
    let oauth_suffix = if custom_oauth { "-custom-oauth" } else { "" };
    let config_suffix = if config_dir_overridden {
        let normalized = config_dir.to_string_lossy().nfc().collect::<String>();
        let digest = format!("{:x}", Sha256::digest(normalized.as_bytes()));
        format!("-{}", &digest[..8])
    } else {
        String::new()
    };
    format!("Claude Code{oauth_suffix}-credentials{config_suffix}")
}

/// Persist the exact Keychain service, so a later profile change cannot drift accounts.
pub fn macos_keychain_claude_auth_source_id(service: &str) -> String {
    format!("{MACOS_KEYCHAIN_CLAUDE_AUTH_SOURCE_ID}:{service}")
}

/// Persist the exact credentials-file profile without exposing its filesystem path.
///
/// Making relative paths absolute is important because Claude Code resolves a relative
/// `CLAUDE_CONFIG_DIR` against the process working directory. NFC normalization keeps
/// equivalent Unicode spellings aligned across persistence and provider resolution.
pub fn credentials_file_claude_auth_source_id(config_dir: &Path) -> std::io::Result<String> {
    credentials_file_claude_auth_source_id_against(config_dir, &std::env::current_dir()?)
}

fn credentials_file_claude_auth_source_id_against(
    config_dir: &Path,
    base_dir: &Path,
) -> std::io::Result<String> {
    let path = if config_dir.is_absolute() {
        config_dir.to_path_buf()
    } else {
        base_dir.join(config_dir)
    };
    let absolute = std::path::absolute(path)?;
    let normalized = absolute.to_string_lossy().nfc().collect::<String>();
    let digest = format!("{:x}", Sha256::digest(normalized.as_bytes()));
    Ok(format!("{CREDENTIALS_FILE_CLAUDE_AUTH_SOURCE_ID}:{digest}"))
}

/// Metadata-only status for the managed long-lived token.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ManagedClaudeTokenStatus {
    Missing,
    Stored { updated_at: i64 },
}

/// Secret-free failures from the managed token lifecycle.
#[derive(Debug, Error)]
pub enum ClaudeSubscriptionTokenError {
    #[error("Claude subscription token is empty")]
    Empty,
    #[error("Claude subscription token must be one bounded line")]
    InvalidFormat,
    #[error(transparent)]
    Vault(#[from] VaultError),
}

/// A credential source the user can explicitly select for Claude Plan requests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthSource {
    /// A one-year subscription token generated by `claude setup-token` and held by Corbanu.
    ManagedSubscriptionToken,
    /// The token supplied explicitly through `CLAUDE_CODE_OAUTH_TOKEN`.
    EnvironmentToken,
    /// Claude Code's platform-owned `/login` credential.
    ClaudeCodeLogin,
}

/// Non-secret storage location metadata for a discovered source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthStoreKind {
    CorbanuVault,
    Environment,
    MacosKeychain,
    CredentialsFile,
    LegacyCredentialsFile,
}

/// Health of one discovered source without including credential material.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthHealth {
    Healthy,
    NeedsEnrollment,
    NeedsReauthorization,
    Missing,
    Malformed,
    Unavailable,
}

/// Persisted user choice. `source_id` names a store/account slot, never a secret.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaudeAuthSelection {
    version: u32,
    pub source: ClaudeAuthSource,
    pub source_id: String,
    pub selected_at: i64,
}

impl ClaudeAuthSelection {
    pub fn new(source: ClaudeAuthSource, source_id: impl Into<String>) -> Result<Self, String> {
        Self::new_at(source, source_id, Utc::now().timestamp())
    }

    pub fn new_at(
        source: ClaudeAuthSource,
        source_id: impl Into<String>,
        selected_at: i64,
    ) -> Result<Self, String> {
        let selection = Self {
            version: CLAUDE_AUTH_SELECTION_VERSION,
            source,
            source_id: source_id.into(),
            selected_at,
        };
        selection.validate()?;
        Ok(selection)
    }

    fn validate(&self) -> Result<(), String> {
        if self.version != CLAUDE_AUTH_SELECTION_VERSION {
            return Err(format!(
                "Claude authentication selection version {} is unsupported",
                self.version
            ));
        }
        let id = self.source_id.trim();
        if id.is_empty() || id.len() > MAX_SOURCE_ID_BYTES {
            return Err("Claude authentication source id is invalid".to_string());
        }
        if id.chars().any(char::is_control) {
            return Err("Claude authentication source id contains control characters".to_string());
        }
        Ok(())
    }
}

/// Safe status for a source. Account hints are display metadata such as an email address.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaudeAuthSourceMetadata {
    pub source: ClaudeAuthSource,
    pub source_id: String,
    pub store: ClaudeAuthStoreKind,
    pub health: ClaudeAuthHealth,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_hint: Option<String>,
}

/// Deterministic outcome of resolving an explicit selection against discovered metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClaudeAuthResolution {
    SelectionRequired {
        available: Vec<ClaudeAuthSourceMetadata>,
    },
    Selected(ClaudeAuthSourceMetadata),
    MissingSelected(ClaudeAuthSelection),
    UnhealthySelected(ClaudeAuthSourceMetadata),
    Conflict {
        selection: ClaudeAuthSelection,
        matches: Vec<ClaudeAuthSourceMetadata>,
    },
}

/// Resolve only the exact selected source. This function never falls through to another source.
pub fn resolve_claude_auth_source(
    selection: Option<&ClaudeAuthSelection>,
    discovered: &[ClaudeAuthSourceMetadata],
) -> ClaudeAuthResolution {
    let mut discovered = discovered.to_vec();
    discovered.sort_by(|left, right| {
        (&left.source, &left.source_id, &left.store, &left.health).cmp(&(
            &right.source,
            &right.source_id,
            &right.store,
            &right.health,
        ))
    });
    let Some(selection) = selection else {
        return ClaudeAuthResolution::SelectionRequired {
            available: discovered,
        };
    };
    let matches = discovered
        .into_iter()
        .filter(|candidate| {
            candidate.source == selection.source && candidate.source_id == selection.source_id
        })
        .collect::<Vec<_>>();
    match matches.as_slice() {
        [] => ClaudeAuthResolution::MissingSelected(selection.clone()),
        [selected] if selected.health == ClaudeAuthHealth::Healthy => {
            ClaudeAuthResolution::Selected(selected.clone())
        }
        [selected] => ClaudeAuthResolution::UnhealthySelected(selected.clone()),
        _ => ClaudeAuthResolution::Conflict {
            selection: selection.clone(),
            matches,
        },
    }
}

impl Vault {
    /// Load the selected Claude source. Absence preserves legacy installations unchanged.
    pub fn load_claude_auth_selection(&self) -> Result<Option<ClaudeAuthSelection>, VaultError> {
        self.with_storage_lock(|| {
            let name = claude_auth_selection_secret_name()?;
            let Some(serialized) = self.secrets.get(&SecretScope::Global, &name)? else {
                return Ok(None);
            };
            let selection: ClaudeAuthSelection = serde_json::from_str(&serialized)
                .map_err(|error| VaultError::Storage(error.into()))?;
            selection
                .validate()
                .map_err(|error| VaultError::Storage(anyhow::anyhow!(error)))?;
            Ok(Some(selection))
        })
    }

    /// Atomically persist a metadata-only source choice in the encrypted state substrate.
    pub fn save_claude_auth_selection(
        &self,
        selection: &ClaudeAuthSelection,
    ) -> Result<(), VaultError> {
        selection
            .validate()
            .map_err(|error| VaultError::Storage(anyhow::anyhow!(error)))?;
        self.with_storage_lock(|| {
            let name = claude_auth_selection_secret_name()?;
            let serialized = serde_json::to_string(selection)
                .map_err(|error| VaultError::Storage(error.into()))?;
            self.secrets.set(&SecretScope::Global, &name, &serialized)?;
            Ok(())
        })
    }

    /// Store or replace the managed token without exposing it through metadata.
    pub fn store_managed_claude_subscription_token(
        &self,
        token: String,
    ) -> Result<ManagedClaudeTokenStatus, ClaudeSubscriptionTokenError> {
        let token = Zeroizing::new(token);
        validate_managed_token(token.as_str())?;
        self.with_storage_lock(|| {
            let mut index = self.load_index()?;
            let now = Utc::now().timestamp();
            upsert_managed_token_metadata(&mut index, now)?;
            self.write_secret(MANAGED_CLAUDE_TOKEN_LABEL, token.as_str())?;
            self.save_index(&index)?;
            Ok(ManagedClaudeTokenStatus::Stored { updated_at: now })
        })
        .map_err(Into::into)
    }

    /// Atomically enroll a managed token and select it for Claude Plan requests.
    ///
    /// If any encrypted-store write fails, the previous token, metadata index,
    /// and source selection are restored before the error is returned.
    pub fn enroll_managed_claude_subscription_token(
        &self,
        token: String,
    ) -> Result<ClaudeAuthSelection, ClaudeSubscriptionTokenError> {
        self.enroll_managed_claude_subscription_token_at(
            token,
            Utc::now().timestamp(),
            EnrollmentFailurePoint::None,
        )
    }

    fn enroll_managed_claude_subscription_token_at(
        &self,
        token: String,
        selected_at: i64,
        failure_point: EnrollmentFailurePoint,
    ) -> Result<ClaudeAuthSelection, ClaudeSubscriptionTokenError> {
        #[cfg(not(test))]
        let _ = failure_point;
        let token = Zeroizing::new(token);
        validate_managed_token(token.as_str())?;
        let selection = ClaudeAuthSelection::new_at(
            ClaudeAuthSource::ManagedSubscriptionToken,
            MANAGED_CLAUDE_AUTH_SOURCE_ID,
            selected_at,
        )
        .map_err(|error| VaultError::Storage(anyhow::anyhow!(error)))?;

        self.with_storage_lock(|| {
            let selection_name = claude_auth_selection_secret_name()?;
            let previous_index = self.load_index()?;
            let previous_token = self
                .read_secret(MANAGED_CLAUDE_TOKEN_LABEL)?
                .map(Zeroizing::new);
            let previous_selection = self.secrets.get(&SecretScope::Global, &selection_name)?;
            let mut next_index = previous_index.clone();
            let now = Utc::now().timestamp();
            upsert_managed_token_metadata(&mut next_index, now)?;
            let serialized_selection = serde_json::to_string(&selection)
                .map_err(|error| VaultError::Storage(error.into()))?;

            let mut token_written = false;
            let mut index_written = false;
            let mut selection_write_attempted = false;
            let write_result = (|| -> Result<(), VaultError> {
                self.write_secret(MANAGED_CLAUDE_TOKEN_LABEL, token.as_str())?;
                token_written = true;
                #[cfg(test)]
                if failure_point == EnrollmentFailurePoint::AfterTokenWrite {
                    return Err(VaultError::Storage(anyhow::anyhow!(
                        "injected managed-token enrollment failure after token write"
                    )));
                }
                self.save_index(&next_index)?;
                index_written = true;
                #[cfg(test)]
                if failure_point == EnrollmentFailurePoint::AfterIndexWrite {
                    return Err(VaultError::Storage(anyhow::anyhow!(
                        "injected managed-token enrollment failure after index write"
                    )));
                }
                selection_write_attempted = true;
                self.secrets.set(
                    &SecretScope::Global,
                    &selection_name,
                    &serialized_selection,
                )?;
                Ok(())
            })();

            if let Err(write_error) = write_result {
                let rollback_result = (|| -> Result<(), VaultError> {
                    if token_written {
                        match previous_token.as_deref() {
                            Some(previous_token) => {
                                self.write_secret(MANAGED_CLAUDE_TOKEN_LABEL, previous_token)?;
                            }
                            None => {
                                self.delete_secret(MANAGED_CLAUDE_TOKEN_LABEL)?;
                            }
                        }
                    }
                    if index_written {
                        self.save_index(&previous_index)?;
                    }
                    if selection_write_attempted {
                        match previous_selection.as_deref() {
                            Some(previous_selection) => self.secrets.set(
                                &SecretScope::Global,
                                &selection_name,
                                previous_selection,
                            )?,
                            None => {
                                self.secrets
                                    .delete(&SecretScope::Global, &selection_name)?;
                            }
                        }
                    }
                    Ok(())
                })();
                if rollback_result.is_err() {
                    return Err(VaultError::Storage(anyhow::anyhow!(
                        "managed Claude token enrollment failed and encrypted-state rollback was incomplete"
                    )));
                }
                return Err(write_error);
            }

            Ok(selection.clone())
        })
        .map_err(Into::into)
    }

    /// Inspect only managed-token metadata.
    pub fn managed_claude_subscription_token_status(
        &self,
    ) -> Result<ManagedClaudeTokenStatus, VaultError> {
        match self.show(MANAGED_CLAUDE_TOKEN_LABEL) {
            Ok(metadata) => Ok(ManagedClaudeTokenStatus::Stored {
                updated_at: metadata.updated_at,
            }),
            Err(VaultError::NotFound { .. }) => Ok(ManagedClaudeTokenStatus::Missing),
            Err(error) => Err(error),
        }
    }

    /// Resolve the managed token only inside a short trusted callback.
    pub fn with_managed_claude_subscription_token<T>(
        &self,
        use_token: impl FnOnce(&str) -> T,
    ) -> Result<T, VaultError> {
        self.with_storage_lock(|| {
            let token = self
                .read_secret(MANAGED_CLAUDE_TOKEN_LABEL)?
                .ok_or_else(|| VaultError::NotFound {
                    label: MANAGED_CLAUDE_TOKEN_LABEL.to_string(),
                })?;
            let token = Zeroizing::new(token);
            let _panic_guard = crate::credential_panic::ScopedCredentialPanicGuard::enter();
            let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                use_token(token.as_str())
            }));
            drop(token);
            outcome.map_err(|_| {
                VaultError::Storage(anyhow::anyhow!("managed Claude token callback panicked"))
            })
        })
    }

    /// Remove only Corbanu's managed copy. This does not claim server-side revocation.
    pub fn remove_managed_claude_subscription_token(&self) -> Result<bool, VaultError> {
        self.delete(MANAGED_CLAUDE_TOKEN_LABEL)
    }
}

fn upsert_managed_token_metadata(
    index: &mut crate::VaultIndex,
    now: i64,
) -> Result<(), VaultError> {
    if let Some(metadata) = index.credentials.get_mut(MANAGED_CLAUDE_TOKEN_LABEL) {
        metadata.credential_type = CredentialType::BearerToken;
        metadata.provider = Some("claude-plan".to_string());
        metadata.notes = Some("Managed long-lived Claude subscription token".to_string());
        metadata.revocation_notes = Some(
            "Local removal does not revoke the token; generate a replacement with `claude setup-token`"
                .to_string(),
        );
        metadata.updated_at = now;
    } else {
        let label = crate::normalize_label(MANAGED_CLAUDE_TOKEN_LABEL)?;
        let metadata = crate::VaultCredentialMeta {
            label: label.clone(),
            credential_type: CredentialType::BearerToken,
            provider: Some("claude-plan".to_string()),
            notes: Some("Managed long-lived Claude subscription token".to_string()),
            revocation_notes: Some(
                "Local removal does not revoke the token; generate a replacement with `claude setup-token`"
                    .to_string(),
            ),
            created_at: now,
            updated_at: now,
            storage_backend: crate::StorageBackend::EncryptedSecrets,
        };
        index.credentials.insert(label, metadata);
    }
    Ok(())
}

fn validate_managed_token(token: &str) -> Result<(), ClaudeSubscriptionTokenError> {
    let trimmed = token.trim();
    if trimmed.is_empty() {
        return Err(ClaudeSubscriptionTokenError::Empty);
    }
    if trimmed != token
        || token.len() > MAX_MANAGED_TOKEN_BYTES
        || token.chars().any(char::is_whitespace)
        || token.chars().any(char::is_control)
    {
        return Err(ClaudeSubscriptionTokenError::InvalidFormat);
    }
    Ok(())
}

fn claude_auth_selection_secret_name() -> Result<SecretName, VaultError> {
    SecretName::new(CLAUDE_AUTH_SELECTION_SECRET_NAME).map_err(|error| {
        VaultError::Storage(anyhow::anyhow!(
            "invalid Claude authentication selection secret name: {error}"
        ))
    })
}

#[cfg(test)]
#[path = "claude_auth_tests.rs"]
mod tests;
