//! Metadata-only Claude subscription authentication selection and health contracts.

use chrono::Utc;
use serde::Deserialize;
use serde::Serialize;

use crate::Vault;
use crate::VaultError;
use codex_secrets::SecretName;
use codex_secrets::SecretScope;

const CLAUDE_AUTH_SELECTION_SECRET_NAME: &str = "CLAUDE_AUTH_SELECTION";
const CLAUDE_AUTH_SELECTION_VERSION: u32 = 1;
const MAX_SOURCE_ID_BYTES: usize = 256;

/// A credential source the user can explicitly select for Claude Plan requests.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthSource {
    /// A one-year subscription token generated by `claude setup-token` and held by Corbanu.
    ManagedSubscriptionToken,
    /// The token supplied explicitly through `CLAUDE_CODE_OAUTH_TOKEN`.
    EnvironmentToken,
    /// Claude Code's platform-owned `/login` credential.
    ClaudeCodeLogin,
}

/// Non-secret storage location metadata for a discovered source.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthStoreKind {
    CorbanuVault,
    Environment,
    MacosKeychain,
    CredentialsFile,
    LegacyCredentialsFile,
}

/// Health of one discovered source without including credential material.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaudeAuthHealth {
    Healthy,
    NeedsEnrollment,
    NeedsReauthorization,
    Missing,
    Malformed,
    Unavailable,
}

/// Persisted user choice. `source_id` names a store/account slot, never a secret.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaudeAuthSelection {
    version: u32,
    pub source: ClaudeAuthSource,
    pub source_id: String,
    pub selected_at: i64,
}

impl ClaudeAuthSelection {
    pub fn new(source: ClaudeAuthSource, source_id: impl Into<String>) -> Result<Self, String> {
        Self::new_at(source, source_id, Utc::now().timestamp())
    }

    pub fn new_at(
        source: ClaudeAuthSource,
        source_id: impl Into<String>,
        selected_at: i64,
    ) -> Result<Self, String> {
        let selection = Self {
            version: CLAUDE_AUTH_SELECTION_VERSION,
            source,
            source_id: source_id.into(),
            selected_at,
        };
        selection.validate()?;
        Ok(selection)
    }

    fn validate(&self) -> Result<(), String> {
        if self.version != CLAUDE_AUTH_SELECTION_VERSION {
            return Err(format!(
                "Claude authentication selection version {} is unsupported",
                self.version
            ));
        }
        let id = self.source_id.trim();
        if id.is_empty() || id.len() > MAX_SOURCE_ID_BYTES {
            return Err("Claude authentication source id is invalid".to_string());
        }
        if id.chars().any(char::is_control) {
            return Err("Claude authentication source id contains control characters".to_string());
        }
        Ok(())
    }
}

/// Safe status for a source. Account hints are display metadata such as an email address.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaudeAuthSourceMetadata {
    pub source: ClaudeAuthSource,
    pub source_id: String,
    pub store: ClaudeAuthStoreKind,
    pub health: ClaudeAuthHealth,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_hint: Option<String>,
}

/// Deterministic outcome of resolving an explicit selection against discovered metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClaudeAuthResolution {
    SelectionRequired {
        available: Vec<ClaudeAuthSourceMetadata>,
    },
    Selected(ClaudeAuthSourceMetadata),
    MissingSelected(ClaudeAuthSelection),
    UnhealthySelected(ClaudeAuthSourceMetadata),
    Conflict {
        selection: ClaudeAuthSelection,
        matches: Vec<ClaudeAuthSourceMetadata>,
    },
}

/// Resolve only the exact selected source. This function never falls through to another source.
pub fn resolve_claude_auth_source(
    selection: Option<&ClaudeAuthSelection>,
    discovered: &[ClaudeAuthSourceMetadata],
) -> ClaudeAuthResolution {
    let mut discovered = discovered.to_vec();
    discovered.sort_by(|left, right| {
        (&left.source, &left.source_id, &left.store, &left.health).cmp(&(
            &right.source,
            &right.source_id,
            &right.store,
            &right.health,
        ))
    });
    let Some(selection) = selection else {
        return ClaudeAuthResolution::SelectionRequired {
            available: discovered,
        };
    };
    let matches = discovered
        .into_iter()
        .filter(|candidate| {
            candidate.source == selection.source && candidate.source_id == selection.source_id
        })
        .collect::<Vec<_>>();
    match matches.as_slice() {
        [] => ClaudeAuthResolution::MissingSelected(selection.clone()),
        [selected] if selected.health == ClaudeAuthHealth::Healthy => {
            ClaudeAuthResolution::Selected(selected.clone())
        }
        [selected] => ClaudeAuthResolution::UnhealthySelected(selected.clone()),
        _ => ClaudeAuthResolution::Conflict {
            selection: selection.clone(),
            matches,
        },
    }
}

impl Vault {
    /// Load the selected Claude source. Absence preserves legacy installations unchanged.
    pub fn load_claude_auth_selection(&self) -> Result<Option<ClaudeAuthSelection>, VaultError> {
        self.with_storage_lock(|| {
            let name = claude_auth_selection_secret_name()?;
            let Some(serialized) = self.secrets.get(&SecretScope::Global, &name)? else {
                return Ok(None);
            };
            let selection: ClaudeAuthSelection = serde_json::from_str(&serialized)
                .map_err(|error| VaultError::Storage(error.into()))?;
            selection
                .validate()
                .map_err(|error| VaultError::Storage(anyhow::anyhow!(error)))?;
            Ok(Some(selection))
        })
    }

    /// Atomically persist a metadata-only source choice in the encrypted state substrate.
    pub fn save_claude_auth_selection(
        &self,
        selection: &ClaudeAuthSelection,
    ) -> Result<(), VaultError> {
        selection
            .validate()
            .map_err(|error| VaultError::Storage(anyhow::anyhow!(error)))?;
        self.with_storage_lock(|| {
            let name = claude_auth_selection_secret_name()?;
            let serialized = serde_json::to_string(selection)
                .map_err(|error| VaultError::Storage(error.into()))?;
            self.secrets.set(&SecretScope::Global, &name, &serialized)?;
            Ok(())
        })
    }

    /// Remove only Corbanu's source choice; provider-owned credentials are untouched.
    pub fn clear_claude_auth_selection(&self) -> Result<bool, VaultError> {
        self.with_storage_lock(|| {
            let name = claude_auth_selection_secret_name()?;
            Ok(self.secrets.delete(&SecretScope::Global, &name)?)
        })
    }
}

fn claude_auth_selection_secret_name() -> Result<SecretName, VaultError> {
    SecretName::new(CLAUDE_AUTH_SELECTION_SECRET_NAME).map_err(|error| {
        VaultError::Storage(anyhow::anyhow!(
            "invalid Claude authentication selection secret name: {error}"
        ))
    })
}

#[cfg(test)]
#[path = "claude_auth_tests.rs"]
mod tests;
